Update rust-toolchain version (#1613)
* Update rust-toolchain version
* Fix dead code issues
* Update mc-oblivious deps to 2.2
* Remove unnecessary packed_simd_2 patch
* Fix error[E0557]: feature has been removed
* Fix clippy warning: Rename from_epoch to since_epoch
* Fix duplicate import.
* Fix clippy::to-string-in-format-args: Simplify test_with_logger macro
* Fix clippy::map-flatten
* Fix clippy::single-char-pattern
* Fix clippy::derivable-impls
* Fix clippy::to-string-in-format-args
* Fix clippy::wrong-self-convention
* Fix clippy::unnecessary-lazy-evaluations
* Fix clippy::unnecessary-to-owned
* Fix clippy return_self_not_must_use
* Update android-bindings/makefile to set up rust toolchains
* Fix fog tests
* Update CHANGELOG